mongoConfig:
  url: localhost
  port: 27017
  username: root
  password: example
  database: mooncake 
  connectOptions: authSource=admin
  defaultTimeout: 100
jwtKey: superS3cr#t
encryptKey: littleR@bbitL0veCarrotAndCabbage